# ApertoDNS Status Page Configuration
# Powered by Upptime - https://upptime.js.org

owner: 1r0n3d3v3l0per
repo: apertodns-status

# Sites to monitor
sites:
  - name: ApertoDNS Website
    url: https://www.apertodns.com
    icon: https://developingweb.com/apple-touch-icon.png
    
  - name: ApertoDNS API
    url: https://www.apertodns.com/api/health
    expectedStatusCodes:
      - 200
      
  - name: ApertoDNS Dashboard
    url: https://www.apertodns.com/login

# Status page configuration
status-website:
  cname: status.apertodns.com
  baseUrl: /
  logoUrl: https://developingweb.com/apple-touch-icon.png
  name: ApertoDNS Status
  introTitle: "**ApertoDNS** is currently operational"
  introMessage: This is the official status page for ApertoDNS Dynamic DNS Service. We monitor all critical services and update this page automatically every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: ApertoDNS
      href: https://www.apertodns.com
    - title: Documentation
      href: https://www.apertodns.com/docs
  favicon: https://developingweb.com/apple-touch-icon.png

# Modern theme configuration
theme: light

# Custom CSS for brand consistency
customHeadHtml: |
  <style>
    :root {
      --primary-color: #3b82f6;
      --primary-dark: #2563eb;
      --success-color: #10b981;
      --warning-color: #f59e0b;
      --error-color: #ef4444;
      --bg-color: #f8fafc;
      --card-bg: #ffffff;
      --text-primary: #1e293b;
      --text-secondary: #64748b;
      --border-color: #e2e8f0;
    }
    
    body {
      font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
      min-height: 100vh;
    }
    
    /* Modern header */
    header, .navbar {
      background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%) !important;
      border-bottom: 1px solid rgba(59, 130, 246, 0.3);
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    
    header a, .navbar a {
      color: #f8fafc !important;
      font-weight: 500;
      transition: color 0.2s ease;
    }
    
    header a:hover, .navbar a:hover {
      color: #3b82f6 !important;
    }
    
    /* Status cards */
    .site-card, .monitor, article {
      background: #ffffff;
      border-radius: 12px;
      border: 1px solid #e2e8f0;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
      transition: all 0.3s ease;
      overflow: hidden;
    }
    
    .site-card:hover, .monitor:hover, article:hover {
      box-shadow: 0 10px 25px -5px rgba(59, 130, 246, 0.15);
      border-color: #3b82f6;
      transform: translateY(-2px);
    }
    
    /* Status badges */
    .status-up, .operational, [class*="up"], .badge-success {
      background: linear-gradient(135deg, #10b981 0%, #059669 100%) !important;
      color: white !important;
      border-radius: 20px;
      padding: 4px 12px;
      font-weight: 600;
      font-size: 0.85rem;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .status-down, .degraded, [class*="down"], .badge-danger {
      background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%) !important;
      color: white !important;
      border-radius: 20px;
      padding: 4px 12px;
      font-weight: 600;
    }
    
    /* All systems operational banner */
    .all-ok, .all-systems-go {
      background: linear-gradient(135deg, #10b981 0%, #059669 100%) !important;
      color: white !important;
      border-radius: 12px;
      padding: 20px;
      text-align: center;
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 24px;
      box-shadow: 0 4px 15px rgba(16, 185, 129, 0.3);
    }
    
    /* Uptime percentage */
    .uptime, .percentage {
      font-size: 1.5rem;
      font-weight: 700;
      color: #10b981;
    }
    
    /* Response time */
    .response-time {
      color: #64748b;
      font-size: 0.9rem;
    }
    
    /* Charts */
    .chart-container {
      background: #ffffff;
      border-radius: 12px;
      padding: 20px;
      border: 1px solid #e2e8f0;
    }
    
    /* Timeline/history */
    .timeline, .history {
      background: #f8fafc;
      border-radius: 8px;
      padding: 16px;
    }
    
    /* Buttons */
    button, .btn {
      background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
      color: white;
      border: none;
      border-radius: 8px;
      padding: 10px 20px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s ease;
    }
    
    button:hover, .btn:hover {
      transform: translateY(-1px);
      box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
    }
    
    /* Footer */
    footer {
      background: #0f172a;
      color: #94a3b8;
      padding: 24px;
      margin-top: 48px;
    }
    
    footer a {
      color: #3b82f6;
    }
    
    /* Headings */
    h1, h2, h3 {
      color: #1e293b;
      font-weight: 700;
    }
    
    /* Links */
    a {
      color: #3b82f6;
      text-decoration: none;
      transition: color 0.2s ease;
    }
    
    a:hover {
      color: #2563eb;
    }
    
    /* Responsive improvements */
    @media (max-width: 768px) {
      .site-card, .monitor {
        margin: 12px 0;
      }
    }
  </style>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">

# Branding
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident Report: {0}"
  pastIncidents: Past Incidents
  scheduledMaintenance: Scheduled Maintenance
  overallUptime: Overall Uptime
  responseTime: Response Time
  ms: ms
  loading: Loading...
  
# Commits settings  
commitMessages:
  statusChange: "$EMOJI $SITE is $STATUS"
  graphsUpdate: "Update response time graphs"
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@apertodns.com"
  
# Check frequency (every 5 minutes)
workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 0 * * *"
